# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 07:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MassMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название СМИ')),
            ],
        ),
        migrations.CreateModel(
            name='MassMediaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Тип СМИ')),
                ('count', models.SmallIntegerField(verbose_name='Количество аккредитуемых журналистов')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название СМИ')),
                ('founder', models.CharField(max_length=200, verbose_name='Учредитель')),
                ('statutory_task', models.CharField(max_length=200, verbose_name='Уставные задачи')),
                ('address', models.CharField(max_length=200, verbose_name='Юридический адрес')),
                ('phone', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('mass_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.MassMedia', verbose_name='СМИ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
