# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 14:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0004_auto_20161214_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mass_media',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='massmediatype',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='reporter',
            name='profile',
        ),
        migrations.AddField(
            model_name='massmedia',
            name='address',
            field=models.CharField(default=1, max_length=200, verbose_name='Юридический адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='massmedia',
            name='founder',
            field=models.CharField(default=1, max_length=200, verbose_name='Учредитель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='massmedia',
            name='phone',
            field=models.CharField(default=1, max_length=50, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='massmedia',
            name='statutory_task',
            field=models.CharField(default=1, max_length=200, verbose_name='Уставные задачи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='massmedia',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporter',
            name='mass_media',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.MassMedia'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
