# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 12:58
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20161214_1653'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='massmediatype',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
