# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20161215_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporter',
            name='image',
            field=models.ImageField(upload_to='uploads/', verbose_name='Фото журналиста'),
        ),
    ]
