# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 09:00
from __future__ import unicode_literals

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20161215_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporter',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='image',
            field=models.ImageField(upload_to=account.models.image_upload_to, verbose_name='Фото журналиста'),
        ),
    ]
