# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20161216_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporter',
            name='printed',
            field=models.BooleanField(default=False),
        ),
    ]
