# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20161220_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporter',
            options={'ordering': ['updated', 'added']},
        ),
        migrations.AlterField(
            model_name='massmedia',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Название СМИ'),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='post',
            field=models.CharField(max_length=30, verbose_name='Должность'),
        ),
    ]
