# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20161221_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massmedia',
            name='title',
            field=models.CharField(max_length=35, verbose_name='Название СМИ'),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='post',
            field=models.CharField(max_length=35, verbose_name='Должность'),
        ),
    ]
