# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-18 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='SiteSettings',
        ),
    ]
